# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a003c191d8535a60d804cfc1014f35d02d7817a96ed47b081e418c60ab7b377fb14250dcdc8c643580789e3dbb871bb723d286e9fad507f3daaf5c379396aeb9

test:
  secret_key_base: f38363164eaddc8d9d686329ca387d55602b787bfa2f64afb08752c6ba112160273ddcfe66d8d717e0ada3def95c97d4a08073b2d899f2a0316593f8c8437675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
