import DS from 'ember-data';

export default DS.Model.extend({
  user: DS.belongsTo('user'),
  cashAvailable: DS.attr('string'),
  price: DS.attr('number'),
  closePl: DS.attr('string'),
  currentRequirement: DS.attr('string'),
  dayTradeBuyingPower: DS.attr('string'),
  dividendBalance: DS.attr('string'),
  equity: DS.attr('string'),
  fedCall: DS.attr('string'),
  longLiquidValue: DS.attr('string'),
  longMarketValue: DS.attr('string'),
  maintenanceCall: DS.attr('string'),
  marketValue: DS.attr('string'),
  netValue: DS.attr('string'),
  openPl: DS.attr('string'),
  optionBuyingPower: DS.attr('string'),
  optionLongValue: DS.attr('string'),
  optionRequirement: DS.attr('string'),
  optionShortValue: DS.attr('string'),
  pendingCash: DS.attr('string'),
  pendingOrdersCount: DS.attr('number'),
  sweep: DS.attr('number'),
  shortLiquidValue: DS.attr('string'),
  shortMarketValue: DS.attr('string'),
  stockBuyingPower: DS.attr('string'),
  stockLongValue: DS.attr('string'),
  stockShortValue: DS.attr('string'),
  unclearedFunds: DS.attr('string'),
  unsettledFunds: DS.attr('string'),
  totalCash: DS.attr('string'),
  totalEquity: DS.attr('string'),
  createdAt: DS.attr(),
  updatedAt: DS.attr()
});
